version: "3.9"

services:
  backend:
    build:
      context: ./hack_back/hack_back
      dockerfile: Dockerfile
    ports:
      - "7249:7249"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./hack_front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
